name: Publish pySnowRadar to PyPI when new master release is published

on:
  push:
    branches:
      - pypi-package

jobs:
  build-and-publish:
    name: Build and publish pySnowRadar to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup build env (Python 3.7)
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install wheel to build env
      run: python -m pip install wheel --user
    - name: Build the source dist and wheel
      run: python setup.py sdist bdist_wheel
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/